### PR TITLE
First draft of Docker Compose environment for running tests. All pass.

### PR DESCRIPTION
**Pull request by manning-ncsa**

### CODE REVIEW

**Review by cnweaver — CHANGES_REQUESTED** [review]
There seems to be some dead code in docker-compose.yaml, which it would be nice to clean up. .gitignore also seems to contain a lot of random stuff (for Django, etc.?). It would be good to also clean things out of there that aren't relvant. 

Otherwise this looks fine, and reminds me that I need to write informstion for the readme, whcih I can do after we merge this.

**Comment by manning-ncsa** [comment]
>.gitignore also seems to contain a lot of random stuff (for Django, etc.?). It would be good to also clean things out of there that aren't relvant.

The `.gitignore` file I added is a verbatim copy of [the Python .gitignore file from this dedicated repo](https://github.com/github/gitignore/blob/main/Python.gitignore), where over time people have curated a file relevant to a variety of Python environments. I recommend we merge this now and then you can delete whatever lines concern you.

>There seems to be some dead code in docker-compose.yaml, which it would be nice to clean up.

I plan to uncomment that code to activate the other services now that I have demonstrated that we can reproduce your local build environment sufficiently to pass the tests you wrote. This will disentangle the database and object store from the archiver container definition. Given that the archiver will run in a container when deployed in production, it makes sense to go ahead and use a consistent build for that container now (especially since containerization also offers benefits during development when collaborating, as my work yesterday illustrates).

**Comment by manning-ncsa** [comment]
After reviewing [your archive-ingest repo pull request](https://github.com/scimma/archive-ingest/pull/4), do you want to align this Dockerfile with [that one](https://github.com/scimma/archive-ingest/blob/761893bcdcd836434599205411c92ece193eae04/Dockerfile), where you are building from `scimma/python-service-base:latest`?

**Comment by cnweaver** [comment]
I don't think that is necessary: `python-service-base` is intended to be a light-weight basis for things to be deployed, whereas your dockerfile is, if I understand correctly, only for development, and should never be deployed. Those seem like distinct enough uses that they do not need to be done in the same way, and trying to tie them together might even be counter-productive.

**Comment by manning-ncsa** [comment]
@cnweaver I pushed some minor changes to address your concern about cruft code and verified that the tests pass. We should be able to merge this assuming you don't object to the change in `tests/conftest.py`.

**Review by cnweaver — APPROVED** [review]
If the tests work for you, that seems sufficient to me.

**Comment by manning-ncsa** [comment]
@cnweaver I merged your latest changes (e70134e579efca88ccdab7e96d80f374d38eb4bd) into this branch but now the database tests fail starting at the `test_SQL_db_create` as you can see in the abbreviated test output below. Before I spend more time trying to understand why this is failing now, perhaps you already know why? Maybe a different postgresql binary is needed now than the one [installed in the Dockerfile](https://github.com/manning-ncsa/archive-core/blob/8f7ba8dc5710471e97eea85f98b75c04a33ec7e3/docker/Dockerfile)?

Either way, would you mind merging this pull request to close it so we can move forward without my fork being involved?

```
$ docker compose up --build
[+] Building 75.5s (21/21) FINISHED                                                                                                                         docker:default
 => [archiver internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 1.02kB                                                                                                                                0.0s
 => [archiver internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 83B                                                                                                                                      0.0s
 => [archiver internal] load metadata for docker.io/library/python:3.11                                                                                               0.0s
 => [archiver internal] load build context                                                                                                                            0.0s
 => => transferring context: 719.64kB                                                                                                                                 0.0s
 => [archiver  1/16] FROM docker.io/library/python:3.11                                                                                                               0.0s
 => [archiver  2/16] RUN useradd --create-home --shell /bin/bash worker --uid 1000                                                                                    0.3s
 => [archiver  3/16] RUN wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20230831153116.0.0_amd64.deb -O minio.deb && dpkg -i minio.deb && rm  17.1s
 => [archiver  4/16] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y   postgresql-15           postgresql-common    && rm -rf /var/lib/apt/  18.6s
 => [archiver  5/16] RUN chown -R 102:1000 /var/run/postgresql                                                                                                        0.5s 
 => [archiver  6/16] RUN mkdir /home/worker/src                                                                                                                       0.6s 
 => [archiver  7/16] WORKDIR /home/worker/src                                                                                                                         0.0s 
 => [archiver  8/16] COPY --chown=worker:worker ./docker ./docker                                                                                                     0.0s 
 => [archiver  9/16] RUN pip install -r docker/requirements.txt                                                                                                       2.6s 
 => [archiver 10/16] COPY --chown=worker:worker ./pyproject.toml .                                                                                                    0.0s 
 => [archiver 11/16] RUN python docker/install_deps.py                                                                                                                0.5s 
 => [archiver 12/16] RUN cat /tmp/requirements.txt && pip install -r /tmp/requirements.txt                                                                           19.7s 
 => [archiver 13/16] COPY --chown=worker:worker ./tests/requirements.txt /tmp/requirements.test.txt                                                                   0.0s 
 => [archiver 14/16] RUN pip install -r /tmp/requirements.test.txt                                                                                                    3.7s 
 => [archiver 15/16] COPY --chown=worker:worker ./ ./                                                                                                                 0.0s 
 => [archiver 16/16] RUN pip install .                                                                                                                               10.0s 
 => [archiver] exporting to image                                                                                                                                     1.6s 
 => => exporting layers                                                                                                                                               1.6s 
 => => writing image sha256:23f53f8323dbb4f190de96e2a523e34523d45e5799b51214e481ec5e1b7cc8e8                                                                          0.0s 
 => => naming to docker.io/library/archive-core:dev                                                                                                                   0.0s 
[+] Running 2/2                                                                                                                                                            
 ✔ Network archive-core_internal  Created                                                                                                                             0.1s 
 ✔ Container archiver             Created                                                                                                                             0.0s 
Attaching to archiver
archiver  | python -m pytest -v --cov=archive --cov-report=term-missing tests
archiver  | ============================= test session starts ==============================
archiver  | platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0 -- /usr/local/bin/python
archiver  | cachedir: .pytest_cache
archiver  | rootdir: /home/worker/src
archiver  | plugins: asyncio-0.21.1, cov-4.1.0, anyio-3.7.1
archiver  | asyncio: mode=Mode.STRICT
archiver  | collecting ... collected 65 items
archiver  | 
archiver  | tests/test_access_api.py::test_add_parser_options PASSED                 [  1%]
archiver  | tests/test_access_api.py::test_archive_access_startup_shutdown PASSED    [  3%]
archiver  | tests/test_access_api.py::test_archive_access_store_message PASSED       [  4%]
archiver  | tests/test_access_api.py::test_archive_access_store_message_no_uuid PASSED [  6%]
archiver  | tests/test_access_api.py::test_archive_access_store_message_duplicate_uuid PASSED [  7%]
archiver  | tests/test_access_api.py::test_archive_access_store_message_duplicate_wo_uuid PASSED [  9%]
archiver  | tests/test_access_api.py::test_archive_access_get_metadata PASSED        [ 10%]
archiver  | tests/test_access_api.py::test_archive_access_get_metadata_for_time_range PASSED [ 12%]
archiver  | tests/test_access_api.py::test_archive_access_get_object_lazily PASSED   [ 13%]
archiver  | tests/test_access_api.py::test_archive_access_get_raw_object PASSED      [ 15%]
archiver  | tests/test_access_api.py::test_archive_access_get_all PASSED             [ 16%]
archiver  | tests/test_access_api.py::test_archive_access_get_as_sent PASSED         [ 18%]
archiver  | tests/test_access_api.py::test_archive_access_get_object_summary PASSED  [ 20%]
archiver  | tests/test_consumer_api.py::test_ConsumerFactory PASSED                  [ 21%]
archiver  | tests/test_consumer_api.py::test_add_parser_options PASSED               [ 23%]
archiver  | tests/test_consumer_api.py::test_hop_consumer_create PASSED              [ 24%]
archiver  | tests/test_consumer_api.py::test_hop_consumer_create_local PASSED        [ 26%]
archiver  | tests/test_consumer_api.py::test_hop_consumer_create_secret PASSED       [ 27%]
archiver  | tests/test_consumer_api.py::test_hop_consumer_create_no_creds PASSED     [ 29%]
archiver  | tests/test_consumer_api.py::test_hop_consumer_create_random_group PASSED [ 30%]
archiver  | tests/test_consumer_api.py::test_hop_consumer_refresh_url PASSED         [ 32%]
archiver  | tests/test_consumer_api.py::test_hop_consumer_get_next PASSED            [ 33%]
archiver  | tests/test_consumer_api.py::test_Base_consumer_unimplemented PASSED      [ 35%]
archiver  | tests/test_consumer_api.py::test_Mock_consumer PASSED                    [ 36%]
archiver  | tests/test_database_api.py::test_DbFactory PASSED                        [ 38%]
archiver  | tests/test_database_api.py::test_add_parser_options PASSED               [ 40%]
archiver  | tests/test_database_api.py::test_SQL_db_startup PASSED                   [ 41%]
archiver  | tests/test_database_api.py::test_SQL_db_connect_no_password PASSED       [ 43%]
archiver  | tests/test_database_api.py::test_SQL_db_connect_no_host PASSED           [ 44%]
archiver  | tests/test_database_api.py::test_SQL_db_create FAILED                    [ 46%]
archiver  | tests/test_database_api.py::test_SQL_db_insert_readonly FAILED           [ 47%]
archiver  | tests/test_database_api.py::test_SQL_db_insert FAILED                    [ 49%]
archiver  | tests/test_database_api.py::test_SQL_db_fetch FAILED                     [ 50%]
archiver  | tests/test_database_api.py::test_SQL_db_uuid_in_db FAILED                [ 52%]
archiver  | tests/test_database_api.py::test_SQL_db_exists_in_db FAILED              [ 53%]
archiver  | tests/test_database_api.py::test_SQL_db_uuid_duplicates FAILED           [ 55%]
archiver  | tests/test_database_api.py::test_SQL_db_content_duplicates FAILED        [ 56%]
archiver  | tests/test_database_api.py::test_SQL_db_get_message_id FAILED            [ 58%]
archiver  | tests/test_database_api.py::test_SQL_db_get_message_locations FAILED     [ 60%]
archiver  | tests/test_database_api.py::test_SQL_db_get_message_records_for_time_range FAILED [ 61%]
archiver  | tests/test_database_api.py::test_Base_db_unimlemented PASSED             [ 63%]
archiver  | tests/test_database_api.py::test_Mock_db_get_message_id PASSED           [ 64%]
archiver  | tests/test_database_api.py::test_Mock_db_insert_readonly PASSED          [ 66%]
archiver  | tests/test_database_api.py::test_Mock_db_fetch PASSED                    [ 67%]
archiver  | tests/test_decision_api.py::test_is_content_identical PASSED             [ 69%]
archiver  | tests/test_decision_api.py::test_get_text_uuid PASSED                    [ 70%]
archiver  | tests/test_decision_api.py::test_get_annotations PASSED                  [ 72%]
archiver  | tests/test_decision_api.py::test_is_deemed_duplicate PASSED              [ 73%]
archiver  | tests/test_store_api.py::test_StoreFactory PASSED                        [ 75%]
archiver  | tests/test_store_api.py::test_add_parser_options PASSED                  [ 76%]
archiver  | tests/test_store_api.py::test_S3_store_startup PASSED                    [ 78%]
archiver  | tests/test_store_api.py::test_S3_store_store_get PASSED                  [ 80%]
archiver  | tests/test_store_api.py::test_S3_store_store_readonly PASSED             [ 81%]
archiver  | tests/test_store_api.py::test_S3_store_get_lazily PASSED                 [ 83%]
archiver  | tests/test_store_api.py::test_S3_store_get_object_summary PASSED         [ 84%]
archiver  | tests/test_store_api.py::test_Mock_store_store_readonly PASSED           [ 86%]
archiver  | tests/test_store_api.py::test_Mock_store_deep_delete PASSED              [ 87%]
archiver  | tests/test_store_api.py::test_Base_store_unimplemented PASSED            [ 89%]
archiver  | tests/test_utility_api.py::test_load_toml_config PASSED                  [ 90%]
archiver  | tests/test_utility_api.py::test_load_toml_config_bad PASSED              [ 92%]
archiver  | tests/test_utility_api.py::test_LoadTomlConfig PASSED                    [ 93%]
archiver  | tests/test_utility_api.py::test_EnvDefault PASSED                        [ 95%]
archiver  | tests/test_utility_api.py::test_add_parser_options PASSED                [ 96%]
archiver  | tests/test_utility_api.py::test_make_logging PASSED                      [ 98%]
archiver  | tests/test_utility_api.py::test_terse PASSED                             [100%]
archiver  | 
archiver  | =================================== FAILURES ===================================
archiver  | ______________________________ test_SQL_db_create ______________________________
archiver  | 
archiver  | self = <sqlalchemy.engine.base.Connection object at 0x7fa70036e450>
archiver  | engine = Engine(postgresql+psycopg://:***@localhost:32768/postgres)
archiver  | connection = None, _has_events = None, _allow_revalidate = True
archiver  | _allow_autobegin = True
archiver  | 
archiver  |     def __init__(
archiver  |         self,
archiver  |         engine: Engine,
archiver  |         connection: Optional[PoolProxiedConnection] = None,
archiver  |         _has_events: Optional[bool] = None,
archiver  |         _allow_revalidate: bool = True,
archiver  |         _allow_autobegin: bool = True,
archiver  |     ):
archiver  |         """Construct a new Connection."""
archiver  |         self.engine = engine
archiver  |         self.dialect = dialect = engine.dialect
archiver  |     
archiver  |         if connection is None:
archiver  |             try:
archiver  | >               self._dbapi_connection = engine.raw_connection()
archiver  | 
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:145: 
archiver  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:3292: in raw_connection
archiver  |     return self.pool.connect()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:452: in connect
archiver  |     return _ConnectionFairy._checkout(self)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:1269: in _checkout
archiver  |     fairy = _ConnectionRecord.checkout(pool)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:716: in checkout
archiver  |     rec = pool._do_get()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py:169: in _do_get
archiver  |     with util.safe_reraise():
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:146: in __exit__
archiver  |     raise exc_value.with_traceback(exc_tb)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py:167: in _do_get
archiver  |     return self._create_connection()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:393: in _create_connection
archiver  |     return _ConnectionRecord(self)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:678: in __init__
archiver  |     self.__connect()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:902: in __connect
archiver  |     with util.safe_reraise():
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:146: in __exit__
archiver  |     raise exc_value.with_traceback(exc_tb)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:898: in __connect
archiver  |     self.dbapi_connection = connection = pool._invoke_creator(self)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py:637: in connect
archiver  |     return dialect.connect(*cargs, **cparams)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py:616: in connect
archiver  |     return self.loaded_dbapi.connect(*cargs, **cparams)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg.py:696: in connect
archiver  |     await_only(creator_fn(*arg, **kw))
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:125: in await_only
archiver  |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:185: in greenlet_spawn
archiver  |     value = await result
archiver  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
archiver  | 
archiver  | cls = <class 'psycopg.AsyncConnection'>
archiver  | conninfo = 'host=localhost dbname=postgres port=32768 connect_timeout=130 hostaddr=::1'
archiver  | autocommit = False, prepare_threshold = 5
archiver  | context = <psycopg.adapt.AdaptersMap object at 0x7fa700362f90>
archiver  | row_factory = None, cursor_factory = None
archiver  | kwargs = {'dbname': 'postgres', 'host': 'localhost', 'port': 32768}
archiver  | params = {'connect_timeout': 130, 'dbname': 'postgres', 'host': 'localhost', 'port': 32768}
archiver  | 
archiver  |     @classmethod  # type: ignore[misc] # https://github.com/python/mypy/issues/11004
archiver  |     async def connect(
archiver  |         cls,
archiver  |         conninfo: str = "",
archiver  |         *,
archiver  |         autocommit: bool = False,
archiver  |         prepare_threshold: Optional[int] = 5,
archiver  |         context: Optional[AdaptContext] = None,
archiver  |         row_factory: Optional[AsyncRowFactory[Row]] = None,
archiver  |         cursor_factory: Optional[Type[AsyncCursor[Row]]] = None,
archiver  |         **kwargs: Any,
archiver  |     ) -> "AsyncConnection[Any]":
archiver  |         if sys.platform == "win32":
archiver  |             loop = asyncio.get_running_loop()
archiver  |             if isinstance(loop, asyncio.ProactorEventLoop):
archiver  |                 raise e.InterfaceError(
archiver  |                     "Psycopg cannot use the 'ProactorEventLoop' to run in async"
archiver  |                     " mode. Please use a compatible event loop, for instance by"
archiver  |                     " setting 'asyncio.set_event_loop_policy"
archiver  |                     "(WindowsSelectorEventLoopPolicy())'"
archiver  |                 )
archiver  |     
archiver  |         params = await cls._get_connection_params(conninfo, **kwargs)
archiver  |         timeout = int(params["connect_timeout"])
archiver  |         rv = None
archiver  |         async for attempt in conninfo_attempts_async(params):
archiver  |             try:
archiver  |                 conninfo = make_conninfo(**attempt)
archiver  |                 rv = await cls._wait_conn(cls._connect_gen(conninfo), timeout=timeout)
archiver  |                 break
archiver  |             except e._NO_TRACEBACK as ex:
archiver  |                 last_ex = ex
archiver  |     
archiver  |         if not rv:
archiver  |             assert last_ex
archiver  | >           raise last_ex.with_traceback(None)
archiver  | E           psycopg.OperationalError: connection is bad: :1", port 32768 failed: Cannot assign requested address
archiver  | E           	Is the server running on that host and accepting TCP/IP connections?
archiver  | 
archiver  | ../.local/lib/python3.11/site-packages/psycopg/connection_async.py:133: OperationalError
archiver  | 
archiver  | The above exception was the direct cause of the following exception:
archiver  | 
archiver  | tmpdir = local('/tmp/pytest-of-worker/pytest-0/test_SQL_db_create0')
archiver  | 
archiver  |     @pytest.mark.asyncio
archiver  |     async def test_SQL_db_create(tmpdir):
archiver  |     	expected_columns = {
archiver  |     		"id": "bigint",
archiver  |     		"topic": "text",
archiver  |     		"timestamp": "bigint",
archiver  |     		"uuid": "uuid",
archiver  |     		"size": "integer",
archiver  |     		"key": "text",
archiver  |     		"bucket": "text",
archiver  |     		"crc32": "bigint",
archiver  |     		"is_client_uuid": "boolean",
archiver  |     		"public": "boolean",
archiver  |     		"direct_upload": "boolean",
archiver  |     		"message_crc32": "bigint"
archiver  |     	}
archiver  |     
archiver  |     	with temp_postgres(tmpdir) as db_conf:
archiver  |     		db = database_api.SQL_db(db_conf)
archiver  |     		await db.connect()
archiver  | >   		await db.make_schema()
archiver  | 
archiver  | tests/test_database_api.py:129: 
archiver  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
archiver  | archive/database_api.py:310: in make_schema
archiver  |     async with self.engine.connect() as conn:
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py:125: in __aenter__
archiver  |     return await self.start(is_ctxmanager=True)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py:270: in start
archiver  |     await greenlet_spawn(self.sync_engine.connect)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:190: in greenlet_spawn
archiver  |     result = context.throw(*sys.exc_info())
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:3268: in connect
archiver  |     return self._connection_cls(self)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:147: in __init__
archiver  |     Connection._handle_dbapi_exception_noconnection(
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2430: in _handle_dbapi_exception_noconnection
archiver  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:145: in __init__
archiver  |     self._dbapi_connection = engine.raw_connection()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:3292: in raw_connection
archiver  |     return self.pool.connect()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:452: in connect
archiver  |     return _ConnectionFairy._checkout(self)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:1269: in _checkout
archiver  |     fairy = _ConnectionRecord.checkout(pool)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:716: in checkout
archiver  |     rec = pool._do_get()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py:169: in _do_get
archiver  |     with util.safe_reraise():
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:146: in __exit__
archiver  |     raise exc_value.with_traceback(exc_tb)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py:167: in _do_get
archiver  |     return self._create_connection()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:393: in _create_connection
archiver  |     return _ConnectionRecord(self)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:678: in __init__
archiver  |     self.__connect()
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:902: in __connect
archiver  |     with util.safe_reraise():
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:146: in __exit__
archiver  |     raise exc_value.with_traceback(exc_tb)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py:898: in __connect
archiver  |     self.dbapi_connection = connection = pool._invoke_creator(self)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py:637: in connect
archiver  |     return dialect.connect(*cargs, **cparams)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py:616: in connect
archiver  |     return self.loaded_dbapi.connect(*cargs, **cparams)
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg.py:696: in connect
archiver  |     await_only(creator_fn(*arg, **kw))
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:125: in await_only
archiver  |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
archiver  | ../.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:185: in greenlet_spawn
archiver  |     value = await result
archiver  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
archiver  | 
archiver  | cls = <class 'psycopg.AsyncConnection'>
archiver  | conninfo = 'host=localhost dbname=postgres port=32768 connect_timeout=130 hostaddr=::1'
archiver  | autocommit = False, prepare_threshold = 5
archiver  | context = <psycopg.adapt.AdaptersMap object at 0x7fa700362f90>
archiver  | row_factory = None, cursor_factory = None
archiver  | kwargs = {'dbname': 'postgres', 'host': 'localhost', 'port': 32768}
archiver  | params = {'connect_timeout': 130, 'dbname': 'postgres', 'host': 'localhost', 'port': 32768}
archiver  | 
archiver  |     @classmethod  # type: ignore[misc] # https://github.com/python/mypy/issues/11004
archiver  |     async def connect(
archiver  |         cls,
archiver  |         conninfo: str = "",
archiver  |         *,
archiver  |         autocommit: bool = False,
archiver  |         prepare_threshold: Optional[int] = 5,
archiver  |         context: Optional[AdaptContext] = None,
archiver  |         row_factory: Optional[AsyncRowFactory[Row]] = None,
archiver  |         cursor_factory: Optional[Type[AsyncCursor[Row]]] = None,
archiver  |         **kwargs: Any,
archiver  |     ) -> "AsyncConnection[Any]":
archiver  |         if sys.platform == "win32":
archiver  |             loop = asyncio.get_running_loop()
archiver  |             if isinstance(loop, asyncio.ProactorEventLoop):
archiver  |                 raise e.InterfaceError(
archiver  |                     "Psycopg cannot use the 'ProactorEventLoop' to run in async"
archiver  |                     " mode. Please use a compatible event loop, for instance by"
archiver  |                     " setting 'asyncio.set_event_loop_policy"
archiver  |                     "(WindowsSelectorEventLoopPolicy())'"
archiver  |                 )
archiver  |     
archiver  |         params = await cls._get_connection_params(conninfo, **kwargs)
archiver  |         timeout = int(params["connect_timeout"])
archiver  |         rv = None
archiver  |         async for attempt in conninfo_attempts_async(params):
archiver  |             try:
archiver  |                 conninfo = make_conninfo(**attempt)
archiver  |                 rv = await cls._wait_conn(cls._connect_gen(conninfo), timeout=timeout)
archiver  |                 break
archiver  |             except e._NO_TRACEBACK as ex:
archiver  |                 last_ex = ex
archiver  |     
archiver  |         if not rv:
archiver  |             assert last_ex
archiver  | >           raise last_ex.with_traceback(None)
archiver  | E           sqlalchemy.exc.OperationalError: (psycopg.OperationalError) connection is bad: :1", port 32768 failed: Cannot assign requested address
archiver  | E           	Is the server running on that host and accepting TCP/IP connections?
archiver  | E           (Background on this error at: https://sqlalche.me/e/20/e3q8)
archiver  | 
archiver  | ../.local/lib/python3.11/site-packages/psycopg/connection_async.py:133: OperationalError
archiver  | ----------------------------- Captured stdout call -----------------------------
archiver  | Attempting to start postgres on port 32768
archiver  | ...
archiver  | ...
archiver  | ...
archiver  | ../.local/lib/python3.11/site-packages/psycopg/connection_async.py:133: OperationalError
archiver  | ----------------------------- Captured stdout call -----------------------------
archiver  | Attempting to start postgres on port 32768
archiver  | 
archiver  | ---------- coverage: platform linux, python 3.11.6-final-0 -----------
archiver  | Name                      Stmts   Miss  Cover   Missing
archiver  | -------------------------------------------------------
archiver  | archive/__init__.py           5      0   100%
archiver  | archive/access_api.py        57      0   100%
archiver  | archive/consumer_api.py     121      0   100%
archiver  | archive/database_api.py     244     83    66%   78-85, 311-316, 320-341, 350-355, 361-363, 370-376, 388-397, 403-416, 422, 426-430, 439-443, 453-457, 460-466, 474-483, 488-497, 501-512, 516-530
archiver  | archive/decision_api.py      40      0   100%
archiver  | archive/store_api.py        188      4    98%   146, 217, 227, 252
archiver  | archive/utility_api.py       50      0   100%
archiver  | -------------------------------------------------------
archiver  | TOTAL                       705     87    88%
archiver  | 
archiver  | =========================== short test summary info ============================
archiver  | FAILED tests/test_database_api.py::test_SQL_db_create - sqlalchemy.exc.Operat...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_insert_readonly - sqlalchemy.e...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_insert - sqlalchemy.exc.Operat...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_fetch - sqlalchemy.exc.Operati...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_uuid_in_db - sqlalchemy.exc.Op...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_exists_in_db - sqlalchemy.exc....
archiver  | FAILED tests/test_database_api.py::test_SQL_db_uuid_duplicates - sqlalchemy.e...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_content_duplicates - sqlalchem...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_get_message_id - sqlalchemy.ex...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_get_message_locations - sqlalc...
archiver  | FAILED tests/test_database_api.py::test_SQL_db_get_message_records_for_time_range
archiver  | ======================== 11 failed, 54 passed in 31.18s ========================
archiver  | make: *** [Makefile:11: test] Error 1
archiver exited with code 2
```

**Comment by cnweaver** [comment]
No different version of postgres should be required; I kept using the same one across those changes and all tests continued passing (some after I made the necessary changes to use the different libraries). 

It seems like we shouldn't merge this while it is in a state with broken tests? Have you looked at the postgres logs to see if those calrify why it doesn't seem to start correctly?

**Review by cnweaver — APPROVED** [review]
This seems workable for the moment.

**Pull request merged**
